"""Add order field to SurveyField

Revision ID: 9e0c32f6070a
Revises: b2b862735e0e
Create Date: 2025-06-08 14:46:20.256842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0c32f6070a'
down_revision = 'b2b862735e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # Populate order field based on current id_ ordering within each survey
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE survey_fields 
        SET "order" = field_order.row_num
        FROM (
            SELECT id_, 
                   ROW_NUMBER() OVER (PARTITION BY survey_id ORDER BY id_) as row_num
            FROM survey_fields
        ) field_order
        WHERE survey_fields.id_ = field_order.id_
    """))
    
    # Make order field non-nullable now that all rows have values
    with op.batch_alter_table('survey_fields', schema=None) as batch_op:
        batch_op.alter_column('order', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_fields', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
