"""Add duplicate_of_id column to search_results table

Revision ID: aa62f0947944
Revises: 9e0c32f6070a
Create Date: 2025-06-08 21:48:01.296827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa62f0947944'
down_revision = '9e0c32f6070a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'search_results', ['duplicate_of_id'], ['id_'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duplicate_of_id')

    # ### end Alembic commands ###
