"""Initial schema baseline

Revision ID: b2b862735e0e
Revises: 
Create Date: 2025-06-08 14:45:35.963258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b862735e0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_file', sa.LargeBinary(), nullable=False),
    sa.Column('thumbnail_file', sa.LargeBinary(), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('users',
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_salt', sa.String(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('surveys',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('searches',
    sa.Column('are_results_uploaded', sa.Boolean(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('survey_fields',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('options', sa.String(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('search_results',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('visible_link', sa.String(), nullable=False),
    sa.Column('direct_link', sa.String(), nullable=False),
    sa.Column('image_scraped_state', sa.String(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('completion_state', sa.String(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id_'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('result_fields',
    sa.Column('search_result_id', sa.Integer(), nullable=False),
    sa.Column('survey_field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id_'], ),
    sa.ForeignKeyConstraint(['survey_field_id'], ['survey_fields.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('tags',
    sa.Column('search_result_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('result_fields')
    op.drop_table('search_results')
    op.drop_table('survey_fields')
    op.drop_table('searches')
    op.drop_table('surveys')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###
