"""Drop tags table - remove tag-based filtering system

Revision ID: ce268c879acb
Revises: e2dfa8d26d4b
Create Date: 2025-06-09 22:40:36.900784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce268c879acb'
down_revision = 'e2dfa8d26d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('search_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id_'], name=op.f('tags_search_result_id_fkey')),
    sa.PrimaryKeyConstraint('id_', name=op.f('tags_pkey'))
    )
    # ### end Alembic commands ###
