"""Add token column to sessions table

Revision ID: e2dfa8d26d4b
Revises: aa62f0947944
Create Date: 2025-06-09 20:53:15.817098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2dfa8d26d4b'
down_revision = 'aa62f0947944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add column as nullable first
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))
    
    # Step 2: Generate tokens for existing sessions
    import secrets
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id_ FROM sessions WHERE token IS NULL"))
    session_ids = [row[0] for row in result]
    
    for session_id in session_ids:
        token = secrets.token_urlsafe(32)
        connection.execute(
            sa.text("UPDATE sessions SET token = :token WHERE id_ = :id"),
            {"token": token, "id": session_id}
        )
    
    # Step 3: Make column non-nullable and add unique constraint
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('token', nullable=False)
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
