version: '2.0'

services:
  website:
    build: ../../website/
    image: morphic-website
    restart: unless-stopped
    volumes:
      - ./settings.js:/usr/src/app/build/settings.js
    networks:
      - internal
      - cloudflared
  background_work:
    build: ../../backend/
    image: morphic-background-work
    restart: unless-stopped
    env_file: ./backend.env
    command: python manage.py background_work
    networks:
      - internal
  backend:
    build: ../../backend/
    image: morphic-backend
    restart: unless-stopped
    env_file: ./backend.env
    networks:
      - internal
      - cloudflared
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    env_file: ./postgres.env
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    networks:
      - internal
  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    env_file: ./cloudflared.env
    networks:
      - cloudflared

networks:
  internal:
  cloudflared:
    external: true
